# Generated by Django 4.0 on 2021-12-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_image_url_alter_image_image_alter_image_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
