# Generated by Django 4.0 on 2021-12-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('social', '0003_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='profile_image',
            field=models.ManyToManyField(to='accounts.Profile'),
        ),
    ]
